'use client';
import {useCallback,useEffect,useMemo,useRef,useState} from 'react';

const W=1536,H=969,R=W/H;
const themes=[
 ['Anime Burst','Anime','#ff4d8d','#7657ff','#0a0d1b'],['Shonen Heat','Shonen','#ff5b21','#ffba08','#15100d'],['Shojo Bloom','Shojo','#ff8fc5','#ffd1e7','#6941c6'],['Toon Pop','Cartoons','#ffd60a','#00bbf9','#f15bb5'],['Hero Panel','Superhero','#ff1744','#2736d8','#07080b'],['Deep Orbit','Sci-Fi','#04050b','#15265f','#30c5ff'],['Cyber Neon','Cyberpunk','#090014','#ff00b8','#00f5ff'],['Arcane','Fantasy','#171124','#4e2a84','#d4af37'],['Nightmare','Horror','#030303','#420b13','#b80f0a'],['Redline','Thriller','#080808','#252525','#e63946'],['Comedy Pop','Comedy','#ffcf33','#ff7a00','#ff3d81'],['Afterglow','Romance','#ff6b9f','#c86dd7','#6834d4'],['Cinema','Drama','#101010','#51483f','#c2a878'],['Velocity','Sports','#00b4d8','#0077b6','#081c15'],['Respawn','Gaming','#19002d','#6c00ff','#00ffa3'],['Arcade 84','Retro','#2b1055','#ff4ecd','#00f0ff'],['Obsidian Gold','Luxury','#050505','#17130b','#725d1d'],['Monolith','Minimal','#0c0c0c','#222','#505050']
].map((t,i)=>({id:String(i),name:t[0],genre:t[1],a:t[2],b:t[3],c:t[4]}));
const initial={theme:'0',src:'',label:'Anime Burst',zoom:1,x:0,y:0,fit:'cover',brightness:1,saturation:1,blur:0,chip:true,chipTone:'gold',chipX:.13,chipY:.34,chipScale:1,number:true,numberText:'••••  ••••  ••••  4242',holder:true,holderText:'CARD HOLDER',expiry:true,expiryText:'12/29',brand:true,brandText:'AIR',light:true,vignette:.2,grain:.07,gloss:.18};

const Range=({name,value,min,max,step=.01,onChange})=><label className="range"><span>{name}<b>{Number(value).toFixed(2)}</b></span><input type="range" min={min} max={max} step={step} value={value} onChange={e=>onChange(+e.target.value)}/></label>;
const Toggle=({name,on,value})=><button className={'toggle '+(value?'on':'')} onClick={()=>on(!value)}><span>{name}</span><i/></button>;
function rr(ctx,x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.closePath()}
function chip(ctx,s){const p={gold:['#f7dc72','#a87918'],silver:['#eef1f3','#7d858c'],black:['#555','#060606'],rose:['#f1b5a8','#815148']}[s.chipTone];const w=240*s.chipScale,h=184*s.chipScale,x=s.chipX*W,y=s.chipY*H;ctx.save();ctx.shadowColor='#0008';ctx.shadowBlur=20;ctx.shadowOffsetY=8;const g=ctx.createLinearGradient(x,y,x+w,y+h);g.addColorStop(0,p[0]);g.addColorStop(1,p[1]);rr(ctx,x,y,w,h,28*s.chipScale);ctx.fillStyle=g;ctx.fill();ctx.shadowColor='transparent';ctx.strokeStyle=p[1];ctx.lineWidth=7*s.chipScale;ctx.beginPath();ctx.moveTo(x+w/2,y+8);ctx.lineTo(x+w/2,y+h-8);ctx.moveTo(x+8,y+h/2);ctx.lineTo(x+w-8,y+h/2);ctx.stroke();for(const q of [.25,.75]){ctx.beginPath();ctx.moveTo(x+w*q,y+8);ctx.lineTo(x+w*q,y+h*.3);ctx.quadraticCurveTo(x+w/2,y+h*.36,x+w/2,y+h/2);ctx.stroke();ctx.beginPath();ctx.moveTo(x+w*q,y+h-8);ctx.lineTo(x+w*q,y+h*.7);ctx.quadraticCurveTo(x+w/2,y+h*.64,x+w/2,y+h/2);ctx.stroke()}ctx.restore()}

export default function Page(){
 const [tab,setTab]=useState('art'),[s,setS]=useState(initial),[img,setImg]=useState(null),[kind,setKind]=useState('anime'),[q,setQ]=useState(''),[results,setResults]=useState([]),[busy,setBusy]=useState(false),[status,setStatus]=useState('Ready for AirCard');
 const canvas=useRef(null),file=useRef(null),pts=useRef(new Map()),last=useRef(null),pinch=useRef(null);
 const theme=useMemo(()=>themes.find(t=>t.id===s.theme)||themes[0],[s.theme]);
 const set=(k,v)=>setS(a=>({...a,[k]:v}));
 useEffect(()=>{try{const v=localStorage.getItem('aircard-studio');if(v){const a=JSON.parse(v);setS(x=>({...x,...a,src:a.src?.startsWith('/api/image?')?a.src:''}))}}catch{}},[]);
 useEffect(()=>{const a={...s,src:s.src.startsWith('/api/image?')?s.src:''};localStorage.setItem('aircard-studio',JSON.stringify(a))},[s]);
 useEffect(()=>{if(!s.src){setImg(null);return}const im=new Image();im.onload=()=>{setImg(im);setStatus('Artwork loaded')};im.onerror=()=>setStatus('Artwork failed to load');im.src=s.src},[s.src]);
 const draw=useCallback((ctx,w=W,h=H)=>{ctx.save();ctx.clearRect(0,0,w,h);ctx.scale(w/W,h/H);let g=ctx.createLinearGradient(0,0,W,H);g.addColorStop(0,theme.a);g.addColorStop(.5,theme.b);g.addColorStop(1,theme.c);ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.globalAlpha=.18;for(let i=0;i<14;i++){ctx.fillStyle=i%2?'#fff':'#000';ctx.beginPath();ctx.arc((i*311)%W,(i*173)%H,90+(i%5)*45,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1;if(img){const ir=img.width/img.height;let iw,ih;if((s.fit==='cover'&&ir>R)||(s.fit==='contain'&&ir<R)){ih=H;iw=ih*ir}else{iw=W;ih=iw/ir}iw*=s.zoom;ih*=s.zoom;ctx.filter=`blur(${s.blur*6}px) brightness(${s.brightness}) saturate(${s.saturation})`;ctx.drawImage(img,(W-iw)/2+s.x*W,(H-ih)/2+s.y*H,iw,ih);ctx.filter='none'}if(s.vignette){g=ctx.createRadialGradient(W/2,H/2,W*.18,W/2,H/2,W*.75);g.addColorStop(0,'#0000');g.addColorStop(1,`rgba(0,0,0,${s.vignette})`);ctx.fillStyle=g;ctx.fillRect(0,0,W,H)}if(s.gloss){g=ctx.createLinearGradient(0,0,W,H);g.addColorStop(0,`rgba(255,255,255,${s.gloss*.45})`);g.addColorStop(.36,'#fff0');g.addColorStop(1,'#fff0');ctx.fillStyle=g;ctx.fillRect(0,0,W,H)}if(s.grain){ctx.globalAlpha=s.grain;for(let i=0;i<4200;i++){ctx.fillStyle=i%3?'#000':'#fff';ctx.fillRect((i*331)%W,(i*197)%H,2,2)}ctx.globalAlpha=1}if(s.chip)chip(ctx,s);ctx.fillStyle=s.light?'#fff':'#090909';ctx.shadowColor=s.light?'#000b':'#fff6';ctx.shadowBlur=10;if(s.brand){ctx.font='800 64px -apple-system';ctx.textAlign='right';ctx.fillText(s.brandText||'AIR',W-110,130)}if(s.number){ctx.font='600 66px ui-monospace,monospace';ctx.textAlign='left';ctx.fillText(s.numberText,128,690)}ctx.font='650 33px -apple-system';if(s.holder){ctx.textAlign='left';ctx.fillText(s.holderText,130,800)}if(s.expiry){ctx.textAlign='right';ctx.fillText(s.expiryText,W-130,800)}ctx.restore()},[img,s,theme]);
 useEffect(()=>{const c=canvas.current,x=c?.getContext('2d');if(x)draw(x)},[draw]);
 const chooseTheme=t=>{setS(a=>({...a,theme:t.id,src:'',label:t.name,zoom:1,x:0,y:0}));setStatus(t.genre+' template loaded')};
 const upload=e=>{const f=e.target.files?.[0];if(!f)return;setS(a=>({...a,src:URL.createObjectURL(f),label:f.name,zoom:1,x:0,y:0}));setStatus('Photo imported')};
 const search=async()=>{if(q.trim().length<2)return;setBusy(true);setStatus('Searching artwork…');try{const r=await fetch('/api/search?q='+encodeURIComponent(q)+'&kind='+kind),j=await r.json();setResults(j.results||[]);setStatus((j.results||[]).length+' artworks found')}catch{setStatus('Search failed')}setBusy(false)};
 const chooseArt=a=>{setS(x=>({...x,src:a.image,label:a.title,zoom:1,x:0,y:0,fit:'cover'}));setStatus(a.title+' loaded')};
 const down=e=>{e.currentTarget.setPointerCapture(e.pointerId);pts.current.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pts.current.size===1)last.current={x:e.clientX,y:e.clientY};if(pts.current.size===2){const p=[...pts.current.values()];pinch.current=Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y)}};
 const move=e=>{if(!pts.current.has(e.pointerId))return;pts.current.set(e.pointerId,{x:e.clientX,y:e.clientY});if(!img)return;if(pts.current.size===1&&last.current){const r=e.currentTarget.getBoundingClientRect(),dx=e.clientX-last.current.x,dy=e.clientY-last.current.y;setS(a=>({...a,x:a.x+dx/r.width,y:a.y+dy/r.height}));last.current={x:e.clientX,y:e.clientY}}else if(pts.current.size===2){const p=[...pts.current.values()],d=Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y);if(pinch.current){const z=d/pinch.current;setS(a=>({...a,zoom:Math.max(.55,Math.min(4,a.zoom*z))}))}pinch.current=d}};
 const up=e=>{pts.current.delete(e.pointerId);last.current=null;pinch.current=null};
 const output=(w,h)=>{const c=document.createElement('canvas');c.width=w;c.height=h;draw(c.getContext('2d'),w,h);return c};
 const save=(w,h,name)=>output(w,h).toBlob(b=>{if(!b)return;const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);setStatus(w+'×'+h+' PNG exported')},'image/png');
 const share=async()=>{const b=await new Promise(r=>output(W,H).toBlob(r,'image/png'));if(!b)return;const f=new File([b],'cardBackgroundCombined@3x.png',{type:'image/png'});try{if(navigator.share&&(!navigator.canShare||navigator.canShare({files:[f]})))await navigator.share({files:[f],title:'AirCard skin'});else save(W,H,f.name)}catch{}};
 return <main className="app"><header><div><small>AIRCARD</small><h1>Sticker Studio</h1></div><button onClick={()=>{setS(initial);setStatus('New design')}}>New</button></header><section className="preview"><div className="card"><canvas ref={canvas} width={W} height={H} onPointerDown={down} onPointerMove={move} onPointerUp={up} onPointerCancel={up}/>{img&&<em>drag · pinch</em>}</div><div className="status"><i/>{status}<b>{s.label}</b></div></section><section className="controls">
 {tab==='art'&&<div className="panel"><div className="title"><h2>Artwork</h2><button className="accent" onClick={()=>file.current?.click()}>Upload Photo</button><input hidden ref={file} type="file" accept="image/*" onChange={upload}/></div><div className="seg">{[['anime','Anime'],['tv','TV Shows'],['cartoon','Cartoons']].map(([a,b])=><button className={kind===a?'active':''} onClick={()=>setKind(a)} key={a}>{b}</button>)}</div><div className="search"><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&search()} placeholder="Search any anime or show…"/><button onClick={search}>{busy?'…':'Search'}</button></div>{results.length>0&&<div className="results">{results.map(a=><button key={a.id} onClick={()=>chooseArt(a)}><img src={a.image} alt=""/><span>{a.title}<small>{a.subtitle||a.source}</small></span></button>)}</div>}<h3>Built-in genre templates</h3><div className="themes">{themes.map(t=><button key={t.id} onClick={()=>chooseTheme(t)} style={{background:`linear-gradient(135deg,${t.a},${t.b},${t.c})`}}><b>{t.name}</b><small>{t.genre}</small></button>)}</div><p className="credit">TV artwork: TVmaze (CC BY-SA). Anime search: Jikan / MyAnimeList-linked artwork. Rights remain with their respective owners.</p></div>}
 {tab==='layout'&&<div className="panel"><div className="title"><h2>Layout + Chip</h2><button onClick={()=>setS(a=>({...a,zoom:1,x:0,y:0}))}>Center</button></div><div className="seg"><button className={s.fit==='cover'?'active':''} onClick={()=>set('fit','cover')}>Fill</button><button className={s.fit==='contain'?'active':''} onClick={()=>set('fit','contain')}>Fit</button></div><Range name="Zoom" value={s.zoom} min={.55} max={4} onChange={v=>set('zoom',v)}/><Range name="Horizontal" value={s.x} min={-1} max={1} onChange={v=>set('x',v)}/><Range name="Vertical" value={s.y} min={-1} max={1} onChange={v=>set('y',v)}/><Toggle name="Show EMV chip" value={s.chip} on={v=>set('chip',v)}/>{s.chip&&<><div className="chips">{['gold','silver','black','rose'].map(a=><button className={s.chipTone===a?'active':''} onClick={()=>set('chipTone',a)} key={a}>{a}</button>)}</div><Range name="Chip size" value={s.chipScale} min={.65} max={1.5} onChange={v=>set('chipScale',v)}/><Range name="Chip X" value={s.chipX} min={0} max={.72} onChange={v=>set('chipX',v)}/><Range name="Chip Y" value={s.chipY} min={0} max={.72} onChange={v=>set('chipY',v)}/></>}</div>}
 {tab==='details'&&<div className="panel"><div className="title"><h2>Card Details</h2><span>decorative</span></div><Toggle name="Masked card number" value={s.number} on={v=>set('number',v)}/>{s.number&&<input value={s.numberText} onChange={e=>set('numberText',e.target.value.slice(0,30))}/>}<Toggle name="Card holder" value={s.holder} on={v=>set('holder',v)}/>{s.holder&&<input value={s.holderText} onChange={e=>set('holderText',e.target.value.slice(0,24))}/>}<Toggle name="Expiry" value={s.expiry} on={v=>set('expiry',v)}/>{s.expiry&&<input value={s.expiryText} onChange={e=>set('expiryText',e.target.value.slice(0,7))}/>}<Toggle name="Top-right badge" value={s.brand} on={v=>set('brand',v)}/>{s.brand&&<input value={s.brandText} onChange={e=>set('brandText',e.target.value.slice(0,8).toUpperCase())}/>}<div className="seg"><button className={s.light?'active':''} onClick={()=>set('light',true)}>Light text</button><button className={!s.light?'active':''} onClick={()=>set('light',false)}>Dark text</button></div></div>}
 {tab==='finish'&&<div className="panel"><div className="title"><h2>Finish</h2><span>live</span></div><Range name="Brightness" value={s.brightness} min={.45} max={1.6} onChange={v=>set('brightness',v)}/><Range name="Saturation" value={s.saturation} min={0} max={2.2} onChange={v=>set('saturation',v)}/><Range name="Soft focus" value={s.blur} min={0} max={1} onChange={v=>set('blur',v)}/><Range name="Vignette" value={s.vignette} min={0} max={.75} onChange={v=>set('vignette',v)}/><Range name="Film grain" value={s.grain} min={0} max={.25} onChange={v=>set('grain',v)}/><Range name="Gloss" value={s.gloss} min={0} max={.75} onChange={v=>set('gloss',v)}/></div>}
 {tab==='export'&&<div className="panel export"><div className="title"><h2>Export for AirCard</h2><span>exact size</span></div><div className="spec"><b>AirCard @3×</b><strong>1536 × 969 PNG</strong><code>cardBackgroundCombined@3x.png</code></div><button className="share" onClick={share}>Share 3× PNG on iPhone</button><button className="accent full" onClick={()=>save(W,H,'cardBackgroundCombined@3x.png')}>Save 1536×969 PNG</button><button className="full" onClick={()=>save(1024,646,'cardBackgroundCombined@2x.png')}>Save 1024×646 PNG</button><p>The 3× export matches AirCard-iOS’s Wallet skin target exactly.</p></div>}
 </section><nav>{[['art','Art'],['layout','Layout'],['details','Details'],['finish','Finish'],['export','Export']].map(([a,b])=><button className={tab===a?'active':''} onClick={()=>setTab(a)} key={a}><i/>{b}</button>)}</nav></main>
}
