export const BLITZ_INDEX = [
  ['Hunter License Credit Card','hunter-x-hunter-credit-card-cover'],
  ['Uno Reverse Card','uno-reverse-card'],
  ['Ara Ara Spending More Money','ara-ara-spending-more-money'],
  ['Take My Money','take-my-money-1'],
  ['Uno Reverse Card','uno-reverse-card-1'],
  ['Spiegel Credit Card Skins','spiegel-credit-card-skins-covers'],
  ['Konohagakure','konohagakure'],
  ['Bankruptcy Debit Card Covers','bankruptcy-debit-card-covers'],
  ['Tiger King','tiger-king'],
  ['Squid Card Cover','squid-card-cover'],
  ['Terry','terry'],
  ['Uno +4','uno-4'],
  ['WHERES THE FOOD','wheres-the-food'],
  ['Itachi','itachi'],
  ['Stonks','stonks'],
  ['Face Mask On Dollar','face-mask-on-dollar'],
  ['Swipe It Again','swipe-it-again'],
  ['Goy','goy'],
  ['Debit','debit'],
  ['White Marble','white-marble'],
  ['Emerald','emerald'],
  ['Burberry','burberry'],
  ['Dragon Ball','dragon-ball'],
  ['Carbon','carbon'],

  ['Neon','neon'],
  ['Credit','credit'],
  ['Broke af','broke-af'],
  ['Almond Latte','almond-latte'],
  ['Aliuminium','aliuminium'],
  ['Cannabis Weed','cannabis-weed'],
  ['Anime Credit Card Cover','anime-credit-card-cover'],
  ['Lisa Frank Credit Card','lisa-frank-credit-card'],
  ['Mountains','mountains'],
  ['Cyberpunk Streets','cyberpunk-streets'],
  ['Naruto Debit Card Skin','naruto-debit-card-skin'],
  ['Advisory','advisory'],
  ['Kamasutra','kamasutra'],
  ['Beskar','beskar'],
  ['Bye bye money','bye-bye-money'],
  ['Pineapples','pineapples'],
  ['To Babes','to-babes'],
  ['Almost Full','almost-full'],
  ['Bitcoin','bitcoin'],
  ['Flowers','flowers'],
  ['Bells','bells'],
  ['Simp Card Skin','simp-card-skin'],
  ['Hapiness','hapiness'],

  ["We're going shopping skin",'were-going-shopping-skin'],
  ["I'm Home",'im-home'],
  ['Retro Rainbow','retro-rainbow'],
  ['Off debit','off-debit'],
  ['Cowboy Bebop','cowboy-bebop'],
  ['Unicorns','unicorns'],
  ['Dogs Faces','dogs-faces'],
  ['Bryant','bryant'],
  ['Joker','joker'],
  ['Plz send help','plz-send-help'],
  ['Proud American','proud-american'],
  ['No Money','no-money'],
  ['Checkered','checkered'],
  ['Metallic Gold Card Cover','metallic-gold-card-cover'],
  ['Batman','batman'],
  ['R34 GT-R','r34-gt-r'],
  ['Godfather','godfather'],
  ['VIP','vip'],
  ['Money Never Sleeps','money-never-sleeps'],
  ['Artificial Intelligence','artificial-intelligence'],
  ['Pink Camouflage','pink-camouflage'],
  ['XX Black','xx-black'],
  ['You VS Your Bank Account','you-vs-your-bank-account'],

  ['Strawberrys','strawberrys'],
  ['BTS Credit Card','bts-credit-card'],
  ['Hearts','hearts'],
  ['Ganesh','ganesh'],
  ['Boo, you wh!re','boo-you-whre'],
  ['Metallic Mirror Silver Card Skin','metallic-mirror-silver-card-skin'],
  ['Off credit','off-credit'],
  ['Money Talks','money-talks'],
  ['Confused Jackie','confused-jackie'],
  ['Pink Glitter','pink-glitter'],
  ['Doge','doge'],
  ['Camo Lambo','camo-lambo'],
  ['Virus Mask','virus-mask'],
  ['Travelling','travelling'],
  ['Planets','planets'],
  ['Error','error'],
  ['Zhongli Stonks','zhongli-stonks'],
  ['Deku Full Cowling Skin','deku-full-cowling-skin'],
  ['Yu Gi Oh','yu-gi-oh'],
  ['Karma','karma'],
  ['Savings Account','savings-account'],
  ['No Bad Vibes','no-bad-vibes'],
  ['In love with food','in-love-with-food'],
  ['Avocados','avocados'],

  ['Lava','lava'],
  ['Ice Cream','ice-cream'],
  ['Hot Dogs','hot-dogs'],
  ['Football Field','football-field'],
  ['Cash','cash'],
  ['Banking','banking'],
  ['Angel Wings','angel-wings'],
  ['Accounting Fraud','accounting-fraud'],
  ['Melody Heart','melody-heart'],
  ['Porsche','porsche'],
  ['Dodge','dodge'],
  ['Rage Face','rage-face'],
  ['Newspaper','newspaper'],
  ['Hipsters','hipsters'],
  ['Eyes','eyes'],
  ['Cowboys','cowboys'],
  ['Yoga','yoga'],
  ['Whiskey','whiskey'],
  ['Testarossa','testarossa'],
  ['Rust','rust'],
  ['Rhombus','rhombus'],
  ['Rainbow Love','rainbow-love'],
  ['Music','music'],
  ['Food porn','food-porn']
].map(([title, handle], index) => ({
  id: 'blitz-snapshot-' + index + '-' + handle,
  title,
  handle
}));
